### ISSUE TITLE
Dataset Specifications

### ISSUE THREAD

**Issue by RemaDaher** [tan5o/anime2clothing#2]
I prepared the dataset in the folder hierarchy as required. However, it seems that the images are being cropped. I think this is the case because in the checkpoint/project_name/web folder I found cropped images. Unfortunately that affects my training. I am not sure what should the specifications of the dataset images be. Can you please clarify that?

By asking for the specifications I am hoping to answer more specific questions:
- Should the images be grayscale or RGB?
- Should the size of the images have a certain limit or be equal to a specific value?
- Should images in folder a and b have the same size and number of channels (RGB or grayscale)?

If there is also other specifications that I didn't mention and are a requirement please also let me know.

**Comment by tan5o** [comment]
Thanks for your interest.

```
Should the images be grayscale or RGB?
```
I always use RGB images. If you want to use grayscale images, you have to change the data augmentation part in dataset.py and generator and discriminator input/output size.

```
Should the size of the images have a certain limit or be equal to a specific value?
```

I think you can use any size of images. Because all input images are resized before inputting to the model.

```
Should images in folder a and b have the same size and number of channels (RGB or grayscale)?
```
You have to use RGB channels images. However, you can use different sizes of images.

Unfortunately, I don't know why you can't train well.
For reference, the image of a and the image of b that I actually used for training are shown.

a/10011.jpg
![a:10011](https://user-images.githubusercontent.com/20256144/96172296-2ca22400-0f61-11eb-980a-73f68c0858e5.jpg)


b/10011.jpg
![b:10011](https://user-images.githubusercontent.com/20256144/96172308-3166d800-0f61-11eb-9553-53c130fac1b3.jpg)

**Comment by RemaDaher** [comment]
Thank you for your prompt reply. 

I was saving the image data (different dataset then the one you are using), and I kept getting croppped images.. I then realized it is from this part of the code in dataset.py

        self.transform = transforms.Compose([
                          transforms.Resize((int(size*1.1), int(size*1.1))),
                          transforms.RandomRotation(3),
                          transforms.RandomCrop(size),
                          transforms.ColorJitter(hue=.05, saturation=.05),
                          transforms.RandomHorizontalFlip(),
                          transforms.ToTensor(),
                          transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

        self.transform_input = transforms.Compose([
            transforms.Resize((int(256 * 1.1), int(256 * 1.1))),
            transforms.RandomRotation(3),
            transforms.RandomCrop(256),
            transforms.ColorJitter(hue=.05, saturation=.05),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

so I commented the cropping commands and I removed every *1.1 from resize. Then it worked.
